# Site settings
title: 'Patrick Pedersen'
email: 'github@patrickpedersen.tech'
description: "Contemplating my next project...\nor maybe I should just finish the ones I've already started."
url: "https://patrickpedersen.tech"
github_username: 'PatrickPedersen'

# Socials
social_links:
  github:
    platform: GitHub
    url: 'https://github.com/PatrickPedersen'
  linkedin:
    platform: LinkedIn
    url: 'https://www.linkedin.com/in/patrick-j-s-pedersen/'

# languages
languages:
  typescript:
    name: TypeScript
    image: typescript-color.svg
  python:
    name: Python
    image: python-color.svg
  php:
    name: PHP
    image: php-color.svg
  powershell:
    name: PowerShell
    image: powershell-color.svg
  bash:
    name: Bash
    image: bash-color.svg
  terraform:
    name: Terraform
    image: terraform-color.svg


# Tools
tools:
  git:
    name: Git
    image: git-color.svg
  github:
    name: GitHub
    image: github-color.svg
  github_actions:
    name: GitHub Actions
    image: githubactions-color.svg
  azure_devops:
    name: Azure DevOps
    image: azuredevops-color.svg
  nodejs:
    name: Node.js
    image: nodejs-color.svg
  vscode:
    name: Visual Studio Code
    image: vscode-color.svg
  pycharm:
    name: PyCharm
    image: pycharm-color.svg
  intellij:
    name: IntelliJ IDEA
    image: intellijidea-color.svg
  phpstorm:
    name: PhpStorm
    image: phpstorm-color.svg
  sonarqube:
    name: SonarQube
    image: sonarqube-color.svg
  postman:
    name: Postman
    image: postman-color.svg
  
# Monitoring
monitoring:
  prometheus:
    name: Prometheus
    image: prometheus-color.svg
  grafana:
    name: Grafana
    image: grafana-color.svg
  loki:
    name: Loki
    image: loki-color.png

# Platforms
platforms:
  azure:
    name: Microsoft Azure
    image: azure-color.svg
  windows:
    name: Windows
    image: windows-color.svg
  docker:
    name: Docker
    image: docker-color.svg
  kubernetes:
    name: Kubernetes
    image: kubernetes-color.svg
  rockylinux:
    name: Rocky Linux
    image: rockylinux-color.svg
  fedora:
    name: Fedora
    image: fedora-color.svg
  archlinux:
    name: Arch Linux
    image: archlinux-color.svg

# Build settings
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
